"""empty message

Revision ID: 009302774a04
Revises: ac0f42572134
Create Date: 2024-04-07 14:10:39.770988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009302774a04'
down_revision = 'ac0f42572134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_prod_non_ste_liq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liquide_name', sa.String(length=220), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulk_prod_non_ste_semi_solid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semi_solid_name', sa.String(length=220), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulk_prod_non_ste_solid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solid_name', sa.String(length=220), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulk_prod_ste_liq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sterile_liq_name', sa.String(length=220), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulk_prod_ste_lyo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lyophilized_name', sa.String(length=220), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('primary_packaging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pri_packaging_name', sa.String(length=220), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secondary_packaging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sec_packaging_name', sa.String(length=220), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_non_ste_liq',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('non_ste_lyo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_details.id'], ),
    sa.ForeignKeyConstraint(['non_ste_lyo_id'], ['bulk_prod_non_ste_liq.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'non_ste_lyo_id')
    )
    op.create_table('company_non_ste_semi_solid',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('non_ste_semi_solid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_details.id'], ),
    sa.ForeignKeyConstraint(['non_ste_semi_solid_id'], ['bulk_prod_non_ste_semi_solid.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'non_ste_semi_solid_id')
    )
    op.create_table('company_non_ste_solid',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('non_ste_solid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_details.id'], ),
    sa.ForeignKeyConstraint(['non_ste_solid_id'], ['bulk_prod_non_ste_solid.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'non_ste_solid_id')
    )
    op.create_table('company_primary_packaging',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('pri_packaging_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_details.id'], ),
    sa.ForeignKeyConstraint(['pri_packaging_id'], ['primary_packaging.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'pri_packaging_id')
    )
    op.create_table('company_secondary_packaging',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sec_packaging_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_details.id'], ),
    sa.ForeignKeyConstraint(['sec_packaging_id'], ['secondary_packaging.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'sec_packaging_id')
    )
    op.create_table('company_sterile_liquide',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ste_liq_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_details.id'], ),
    sa.ForeignKeyConstraint(['ste_liq_id'], ['bulk_prod_ste_liq.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'ste_liq_id')
    )
    op.create_table('company_sterile_lyophilized',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ste_lyo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_details.id'], ),
    sa.ForeignKeyConstraint(['ste_lyo_id'], ['bulk_prod_ste_lyo.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'ste_lyo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_sterile_lyophilized')
    op.drop_table('company_sterile_liquide')
    op.drop_table('company_secondary_packaging')
    op.drop_table('company_primary_packaging')
    op.drop_table('company_non_ste_solid')
    op.drop_table('company_non_ste_semi_solid')
    op.drop_table('company_non_ste_liq')
    op.drop_table('secondary_packaging')
    op.drop_table('primary_packaging')
    op.drop_table('bulk_prod_ste_lyo')
    op.drop_table('bulk_prod_ste_liq')
    op.drop_table('bulk_prod_non_ste_solid')
    op.drop_table('bulk_prod_non_ste_semi_solid')
    op.drop_table('bulk_prod_non_ste_liq')
    # ### end Alembic commands ###
